//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibBuilder.WPFCore {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Color : global::System.Configuration.ApplicationSettingsBase {
        
        private static Color defaultInstance = ((Color)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Color())));
        
        public static Color Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Light")]
        public global::MaterialDesignThemes.Wpf.BaseTheme Theme {
            get {
                return ((global::MaterialDesignThemes.Wpf.BaseTheme)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teal")]
        public global::MaterialDesignColors.PrimaryColor Primary {
            get {
                return ((global::MaterialDesignColors.PrimaryColor)(this["Primary"]));
            }
            set {
                this["Primary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public global::MaterialDesignColors.SecondaryColor Secondary {
            get {
                return ((global::MaterialDesignColors.SecondaryColor)(this["Secondary"]));
            }
            set {
                this["Secondary"] = value;
            }
        }
    }
}
